workflows:
  build_movix:
    name: Build Movix App
    max_build_duration: 60

    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN

    scripts:
      - npm install
      - npx expo prebuild
      - npx expo export
      # منع تشغيل emulator نهائياً
      - npx expo run:android --variant release --no-install

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - abdessamadhcabadi@gmail.com
