workflows:
  expo-android:
    name: Expo Android APK Build
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g expo-cli
      - name: Build APK using old Expo CLI
        script: |
          expo build:android -t apk --non-interactive
    artifacts:
      - dist/**/*.apk
      - build/**/*.apk
