workflows:
  android:
    name: EAS Android APK Build
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Login to Expo
        script: |
          npx eas login --token $EXPO_TOKEN

      - name: Build APK with EAS
        script: |
          npx eas build --platform android --profile production --non-interactive

    artifacts:
      - build/**/*.apk
      - dist/**/*.apk
